export const PAST_LAUNCHES_REQUEST_BODY = {
    query: {
        upcoming: false,
    },
    options: {
        limit: 100,
        sort: {
            flight_number: 'desc',
        },
        select: {
            _id: 1,
            name: 1,
            flight_number: 1,
            details: 1,
            date_unix: 1,
            date_precision: 1,
            rocket: 1,
            payloads: 1,
            launchpad: 1,
            'links.patch.large': 1,
            'links.flickr.original': 1,
            'links.youtube_id': 1,
            'cores.flight': 1,
            'cores.landing_attempt': 1,
            'cores.landing_type': 1,
            'cores.landpad': 1,
        },
        populate: [
            {
                path: 'rocket',
                select: {
                    _id: 0,
                    name: 1,
                    'height.meters': 1,
                    'diameter.meters': 1,
                    stages: 1,
                    boosters: 1,
                    cost_per_launch: 1,
                    'engines.number': 1,
                    'engines.type': 1,
                    'engines.layout': 1,
                    'engines.propellant_1': 1,
                    'engines.propellant_2': 1,
                    flickr_images: 1,
                },
            },
            {
                path: 'payloads',
                select: {
                    _id: 0,
                    name: 1,
                    type: 1,
                    customers: 1,
                    nationalities: 1,
                    manufacturers: 1,
                    mass_kg: 1,
                    orbit: 1,
                    regime: 1,
                },
            },
            {
                path: 'launchpad',
                select: {
                    _id: 0,
                    name: 1,
                    full_name: 1,
                    locality: 1,
                    region: 1,
                    timezone: 1,
                    'images.large': 1,
                },
            },
            {
                path: 'cores.landpad',
                select: {
                    _id: 0,
                    name: 1,
                    full_name: 1,
                    locality: 1,
                    region: 1,
                    type: 1,
                    'images.large': 1,
                },
            },
        ],
    },
};
